### ISSUE TITLE
grafica nuova call to action

### ISSUE THREAD

**Issue by dontyna** [ondata/cipassalafame#15]
si potrebbe pensare a un nuovo colore per la sezione del sito con le nuove proposte a partecipare? Così si perde un po'.

**Comment by aborruso** [comment]
@dontyna ho fatto una cosetta, ma è meglio che lo faccia tuo ...  :)

Al momento è gestito da questo stile https://github.com/ondata/cipassalafame/blob/0df71250476543558b927232ba61e01f20a81c20/css/stylish-portfolio.css#L397-L399

**Comment by dontyna** [comment]
ora c'è un'immagine di sfondo
