### ISSUE TITLE
Evento FB

### ISSUE THREAD

**Issue by dontyna** [ondata/cipassalafame#6]
1. togliere bottone "guarda l'evento facebook"
2. aggiungere nuovo primo punto ai modi per partecipare: 

- Segna "partecipa" all['evento su Facebook](https://www.facebook.com/events/345025692894118/346000942796593/) e condividilo nella tua rete.

- Fai sapere che aderisci all’iniziativa compilando questo form ...

**Comment by dontyna** [comment]
C'è un errore nel link per colpa mia, quello giusto è questo: https://www.facebook.com/events/345025692894118/ Sorry! @aborruso

**Comment by aborruso** [comment]
corretto @dontyna
