### ISSUE TITLE
Chi siamo

### ISSUE THREAD

**Issue by dontyna** [ondata/cipassalafame#7]
**Attivisti:** 
Martina Cera, Donata Columbro, Claudia Vago, Claudio Riccio, Giulio Cocchini.
**Sito e mappa:**
 Andrea Borruso, Matteo Tempestini, Alessandro Rizzo.

**Primi aderenti:**
Daniele Biella (giornalista), Riccardo Bonacina (Vita non profit), Igiaba Scego (scrittrice), Fabio Geda (scrittore), Sara Consolato (attivista), Francesco Malvolta (fotoreporter), Ilaria Roberta Sesana (giornalista), Paolo Di Paolo (scrittore), Dino Amenduni (comunicatore politico), Giulio Cavalli (giornalista), Violetta Bellocchio (scrittrice), Barbara Antonelli (Responsabile Comunicazione ActionAid), Raffaella Maria Cosentino (Giornalista), John Mpaliza (attivista).

**Organizzazioni:**
Refugees Welcome Italia, Action Aid Italia, Centro Studi Sereno Regis, Pianoterra Onlus, Chiama L'Africa, Cooperativa Sociale Progetto Tenda ONLUS, Haki Tumaini, CISV Onlus, Centro Ricerca e Intervento Sociale, COSPE Onlus, Zalib & I Ragazzi di Via della Gatta, FOCSIV, Gli Anelli Mancanti ONLUS, Voci Globali, LVIA, onData, A Buon Diritto.

**Comment by iltempe** [comment]
fatto.
